// The name of every clickable element in the film, and where on the site it leads when the storyboard's
// Targets row does not say (or says too broadly). Keys are the elements' data-target ids; the list is
// checked against the film by video/animation/scripts/targets.mjs (every id named, every location real).
// [name, location?] — a location is a content file with an optional heading anchor.
export const TARGETS: Record<string, [string, string?]> = {
  // The landscape: the four kinds of knowledge, their custodians, their documents and the sprint flow.
  'knowledge.functional': ['Functional knowledge', 'sdlc/translation-tax.md#the-product-owner'],
  'knowledge.design': ['Design knowledge', 'sdlc/translation-tax.md#the-ux-designer'],
  'knowledge.architecture': ['Architecture knowledge', 'sdlc/translation-tax.md#the-architect'],
  'knowledge.code': ['Code knowledge', 'sdlc/translation-tax.md#the-engineering-team'],
  'custodian.functional': ['The product owner', 'sdlc/translation-tax.md#the-product-owner'],
  'custodian.design': ['The UX designer', 'sdlc/translation-tax.md#the-ux-designer'],
  'custodian.architecture': ['The architect', 'sdlc/translation-tax.md#the-architect'],
  'custodian.code': ['The engineering team', 'sdlc/translation-tax.md#the-engineering-team'],
  'artifact.functional': ['Prose specifications', 'sdlc/translation-tax.md#the-landscape-today'],
  'artifact.design': ['Design handoffs', 'sdlc/translation-tax.md#the-landscape-today'],
  'artifact.architecture': ['The architecture wiki', 'sdlc/translation-tax.md#why-documentation-does-not-fix-it'],
  'artifact.code': ['Code knowledge held in people’s heads', 'sdlc/translation-tax.md#the-engineering-team'],
  'flow.spec': ['The specification', 'sdlc/process/implementation-sprint.md#the-per-change-sdlc-flow'],
  'flow.dev': ['The developer', 'sdlc/process/implementation-sprint.md#the-per-change-sdlc-flow'],
  'flow.review': ['Code review', 'sdlc/translation-tax.md#the-landscape-today'],
  'flow.merge': ['Merge', 'sdlc/translation-tax.md#the-landscape-today'],
  'flow.coding-agent': ['The AI coding agent', 'sdlc/translation-tax.md#why-ai-coding-agents-stall-on-this'],
  'sprint.conventional': ['A conventional Scrum sprint', 'sdlc/translation-tax.md#what-this-looks-like-on-a-sprint'],

  // Act 1: the problem.
  'problem.knowledge': ['Knowledge an agent cannot read', '_index.md#the-shared-problem'],
  'need.four-kinds': ['Four kinds of knowledge before the right code', 'sdlc/translation-tax.md#what-the-custodians-know-that-the-code-does-not-show'],
  'tax.unrecorded': ['Knowledge passed between two people, unrecorded', 'sdlc/translation-tax.md#how-it-shows-up-in-a-sprint'],
  'tax.definition': ['The Manual Translation Tax'],
  'tax.ai': ['Faster code, the same delivery', 'sdlc/translation-tax.md#why-ai-coding-agents-stall-on-this'],
  'need.change-medium': ['Changing how knowledge is recorded', 'sdlc/translation-tax.md#the-structural-response'],
  'need.structured-context': ['What the agent needs'],
  'fig.typing-to-reading': ['Twenty minutes of typing becomes ninety seconds', 'sdlc/zones/zone-1-manual-vibe-coding.md#what-the-team-operates-with'],
  'fig.design-30s': ['Thirty seconds to name the right control', 'sdlc/translation-tax.md#what-this-looks-like-on-a-sprint'],
  'fig.wiki-9-months': ['A wiki nine months out of date', 'sdlc/translation-tax.md#what-this-looks-like-on-a-sprint'],
  'fig.ping-cost': ['The cost of each message'],
  'example.contradiction': ['An answer that contradicts the wiki', 'sdlc/translation-tax.md#what-this-looks-like-on-a-sprint'],
  'example.colleague-away': ['A colleague away until Monday', 'sdlc/translation-tax.md#what-this-looks-like-on-a-sprint'],
  'example.production-defect': ['A defect six weeks later', 'sdlc/translation-tax.md#what-this-looks-like-on-a-sprint'],
  'example.ambiguity': ['Ambiguity: two weeks of work partly redone', 'sdlc/translation-tax.md#the-three-components-of-the-tax'],
  'example.non-persistence': ['Non-persistence: months of rediscovery', 'sdlc/translation-tax.md#the-three-components-of-the-tax'],
  'example.non-traceability': ['Non-traceability: two days to find the cause', 'sdlc/translation-tax.md#the-three-components-of-the-tax'],
  'example.agent-session': ['Every agent session starts empty', 'sdlc/translation-tax.md#why-ai-coding-agents-stall-on-this'],
  'decay.documentation': ['More documentation decays the same way'],
  'fig.docs-40-percent': ['Architecture pages out of date by year end'],
  'agent.context-limit': ['What the agent can read'],
  'agent.cannot-ask': ['The agent cannot ask', 'sdlc/translation-tax.md#why-ai-coding-agents-stall-on-this'],
  'agent.invisible': ['Knowledge invisible to the agent', 'sdlc/translation-tax.md#why-ai-coding-agents-stall-on-this'],
  'agent.small-tasks': ['Small, contained tasks', 'sdlc/zones/zone-1-manual-vibe-coding.md#when-this-zone-is-genuinely-suitable'],
  'agent.enterprise': ['Enterprise complexity', 'sdlc/zones/zone-1-manual-vibe-coding.md#when-this-zone-stops-working'],
  'agent.context-windows': ['Bigger context windows', '_index.md#the-shared-problem'],
  'example.removed-function': ['A call to a removed function'],
  'fig.no-global-gain': ['No overall gain on two million lines', 'sdlc/case-archetypes.md#brownfield-enterprise-modernization'],
  'fig.negative-gain': ['A negative gain once the back-and-forth counted', 'sdlc/translation-tax.md#why-ai-coding-agents-stall-on-this'],
  'usecase.same-gap': ['The same gap in every kind of work', '_index.md#the-shared-problem'],

  // Act 2: the methodology and the graph.
  'graph': ['The knowledge graph', '_index.md#the-methodology'],
  'graph.layer.functional': ['The functional layer', 'sdlc/methodology.md#the-functional-ontology-in-detail'],
  'graph.layer.design': ['The design layer', 'sdlc/methodology.md#the-design-ontology-in-detail'],
  'graph.layer.architecture': ['The architecture layer', 'sdlc/methodology.md#the-architecture-ontology-in-detail'],
  'graph.layer.code': ['The code layer', 'sdlc/methodology.md#the-code-ontology-in-detail'],
  'graph.ontology': ['Each layer is an ontology', 'sdlc/methodology.md#the-four-layer-ontology'],
  'graph.citations': ['Every item cites its source', 'sdlc/methodology.md#citations-at-every-layer'],
  'fig.traversal-email-alerts': ['What one search found for one user story', 'sdlc/methodology.md#cross-layer-traversal'],
  'principle.structured': ['Principle 1: one structured graph', 'sdlc/methodology.md#queryability-and-the-token-economy'],
  'principle.ownership': ['Principle 3: a named owner for each part', 'sdlc/process/team.md#the-layered-team-structure'],
  'gate.validation': ['The validation gate', 'sdlc/methodology.md#the-validation-gate'],
  'gate.evidence': ['Every check is recorded for audit', 'sdlc/agents.md#the-override-audit-trail'],
  'aperture': ['The aperture'],
  'aperture.burden': ['Everything in the graph', 'sdlc/methodology.md#aperture'],
  'aperture.blast-radius': ['Blast radius'],
  'aperture.include': ['A wide blast radius belongs in the graph', 'sdlc/methodology.md#high-aperture-and-low-aperture-elements-by-layer'],
  'aperture.exclude': ['A local detail stays in the specification and code', 'sdlc/methodology.md#high-aperture-and-low-aperture-elements-by-layer'],
  'aperture.default-exclude': ['When unsure, it stays out', 'sdlc/methodology.md#the-decision-rule'],
  'aperture.matures': ['The aperture widens over time', 'sdlc/methodology.md#how-the-aperture-matures'],
  'graph.partition': ['One graph per product', 'sdlc/methodology.md#partition-by-product'],
  'graph.integration-points': ['Links where products integrate', 'sdlc/methodology.md#cross-product-reasoning'],
  'agent.pr-validation': ['The PR Validation Agent'],
  'agent.kg-sync': ['The KG Sync Agent'],
  'fig.health': ['The health of the graph', 'sdlc/methodology.md#governance-and-metrics'],
  'governance.p0': ['The most critical checks block a merge', 'sdlc/methodology.md#concrete-thresholds'],
  'custodians.human': ['The custodians stay human'],
  'custodians.inputs': ['Knowledge no agent can read', 'sdlc/translation-tax.md#where-we-draw-the-line-on-automation'],
  'custodians.approve': ['Agents draft, custodians approve', 'sdlc/agents.md#what-triggers-human-review'],
  'custodians': ['A named owner for each layer', 'sdlc/process/team.md#the-layered-team-structure'],

  // Act 3: the buyer questions.
  'spec.one-team': ['A specification for each change', 'sdlc/zones/zone-2-spec-driven-development.md#when-this-zone-is-genuinely-suitable'],
  'limit.local-context': ['Limit: local context'], 'limit.drift': ['Limit: drift from the code'],
  'limit.one-layer': ['Limit: one layer only'], 'limit.bottleneck': ['Limit: writing specifications is the bottleneck'],
  'graph.alongside-spec': ['The graph alongside the specification'],
  'ticket.hook': ['Impact analysis from the ticket system'],
  'ticket.workflow': ['The workflow each team designs', 'sdlc/process/implementation-sprint.md#how-the-ticket-carries-the-change'],
  'sprint.spec': ['The spec sprint', 'sdlc/process/spec-sprint.md#what-happens-in-a-spec-sprint'],
  'sprint.implementation': ['The implementation sprint', 'sdlc/process/implementation-sprint.md#the-per-change-sdlc-flow'],
  'sprint.push-back': ['Back to the spec sprint', 'sdlc/process/spec-sprint.md#the-mechanics'],
  'graph.main-branch': ['The graph matches the main branch', 'sdlc/agents.md#the-kg-sync-agent'],
  'agent.impact-analysis': ['The Impact Analysis Agent'],
  'impact.outputs': ['Two kinds of output'],
  'fig.senior-days': ['Three to five days by hand', 'sdlc/agents.md#a-worked-example'],
  'agent.cannot-ignore': ['The agent cannot ignore the impact report', 'sdlc/agents.md#the-variance-bounding-insight'],
  'variance.bounded': ['The runs differ in detail only'],
  'autonomy.levels': ['The five levels of autonomy'],
  'agents.owner': ['A named owner for every agent', 'sdlc/agents.md#agent-ownership'],
  'workbench.why': ['The agent workbench', 'sdlc/agents.md#high-volume-support-work'],
  'graph.per-product': ['One graph per product'],
  'graph.enterprise-shared': ['Knowledge shared across products'],
  'agent.cross-product': ['Impact across products'],
  'agent.portfolio-rationalization': ['A quarterly look across the products', 'sdlc/methodology.md#extraction-as-rationalization'],
  'extraction.brownfield': ['Extracting the graph from the code'],
  'extraction.patterns': ['What extraction shows'],
  'debt.risk': ['Fast agents, fast technical debt', 'sdlc/methodology.md#paying-down-technical-debt'],
  'fig.extraction': ['Two to three weeks for two million lines'],
  'fig.mtt-survey-60': ['60% named estimation and code comprehension', 'sdlc/case-archetypes.md#where-the-manual-translation-tax-was-paid'],
  'fig.deploys-36': ['Deployments from 19 to 36 a month', 'sdlc/case-archetypes.md#delivery-metrics-before-and-after'],
  'fig.lead-time': ['Lead time from 2.0 to 1.42 days', 'sdlc/case-archetypes.md#delivery-metrics-before-and-after'],
  'fig.impact-replaces-investigation': ['Impact analysis in place of days of investigation', 'sdlc/case-archetypes.md#what-changed-in-how-the-team-works'],
  'fig.reuse-53': ['53% design component reuse'], 'fig.defects-23': ['23% fewer defects'],
  'fig.coverage-93': ['93.4% test coverage'], 'fig.tco-81': ['81% lower five-year cost, modeled'],

  // Act 4: legacy modernization.
  'pipeline.frame': ['The modernization pipeline', 'modernization/_index.md'],
  'card.legacy-code': ['The legacy code'], 'figure.sme': ['Subject-matter experts'],
  'tax.modernization': ['The Modernization Translation Tax', 'modernization/translation-tax.md#the-modernization-version-of-the-problem'],
  'tax.reverse-engineering': ['The reverse-engineering tax'], 'tax.lost-context': ['The lost-context tax'],
  'tax.validation-vacuum': ['The validation-vacuum tax'], 'tax.knowledge-disappearance': ['The knowledge-disappearance tax'],
  'tax.compound': ['The first three compound'], 'token.stalled': ['A modernization that stalls'],
  'ontologies.three': ['Three structured records'],
  'graph.source-state': ['The graph of the old system'], 'graph.target-state': ['The graph of the new system'],
  'node.statement-body': ['Code statements kept as evidence', 'modernization/methodology.md#the-source-state-ontology-in-detail'],
  'spec.format': ['The specification between the two graphs'],
  'annotate.required': ['A decision for every module'], 'annotate.retain': ['Retain'], 'annotate.modify': ['Modify'],
  'annotate.replace': ['Replace'], 'annotate.retire': ['Retire'],
  'contract.parity': ['The parity contract'], 'agent.migration': ['The migration agents'],
  'loop.migration-validation': ['The four validation gates'],
  'gate.architecture': ['The architecture gate'], 'gate.design': ['The design gate'],
  'gate.standards': ['The standards gate'], 'gate.functional': ['The functional gate'],
  'fleet.nine-agents': ['Nine named agents'],
  'stage.discover': ['Discover'], 'stage.document': ['Document'], 'stage.migrate': ['Migrate'],
  'stage.validate': ['Validate'], 'stage.maintain': ['Maintain'],
  'pillar.agie': ['ASIMOV'],
  'modes.why': ['Five engagement modes'], 'modes.stopping-points': ['Stopping at any mode'],
  'fig.asimov-15m-loc': ['15M+ lines modernized'], 'fig.up-to-4x': ['Up to four times faster, indicative'],
  'fig.up-to-70pct': ['Up to 70% less migration time, indicative'], 'fig.java-21-upgrade': ['Java 8 to Java 21'],
  'fig.delphi-net8': ['Delphi to .NET 8'],
  'handover.graph': ['The graph for the modernized system'], 'handover.custodians': ['The same custodians continue'],

  // Act 5, Act 6 and the appendix.
  'phase.advise': ['Advise'], 'phase.launch': ['Launch'], 'phase.scale': ['Scale'], 'phase.optimize': ['Optimize'],
  'partnership.ownership': ['The client owns the graph'], 'offboarding.graph': ['Four commitments for the end of an engagement'],
  'archetype.brownfield': ['Brownfield engagement'], 'archetype.greenfield': ['Greenfield engagement'],
  'archetype.pattern': ['The pattern across the engagements'],
  'fig.brownfield-extraction': ['All four layers in two to three weeks'], 'fig.brownfield-impact': ['Days of investigation replaced'],
  'fig.greenfield-reuse': ['53% reuse in the first sprint'],
  'next.agent-interfaces': ['An interface for agents, built from the graph'],
  'next.dialect-engineering': ['Dialect engineering', 'https://dialect-engineering.ai'],
  'origin.breeze': ['Breeze, 2017'], 'origin.drug-discovery': ['Drug discovery, 2022'], 'origin.kaps': ['KAPS, 2023'],
  'origin.breeze-ai': ['Breeze.AI, 2024'], 'next.public': ['Public and free to apply'], 'next.contact': ['A two-day workshop'],
  'platform.breeze-ai': ['Breeze.AI'],
  'spec.and-graph': ['The specification and the graph', 'sdlc/methodology.md#the-validation-gate'],
  'agent.owners': ['People decide, every agent has an owner', 'sdlc/agents.md#agent-ownership'],
};
